--a clausula if tem por objetivo tentar entregar um comando mais rapido por seleção
--tentar, porque geralmente usamos junção e nem sempre ela é mais rapida
--É MAIS RAPIDO PORQUE TRABALHA COM TEMPO DE EXECUÇÃO EM MEMORIA
-- A CLAUSULA WITH CRIA UM VISÃO TEMPORARIA EM TEMPO DE EXECUÇÃO (GLOBAL TEMPORARY TABLE, ELA SÓ EXISTE EM TEMPO DE EXECUÇÃO)
WITH 
    EMP AS (SELECT * FROM EMPLOYEES)
    --como eu ja tenho minha visão criada, vou consumir da minha visão
SELECT LAST_NAME FROM EMP;

--EU CRIO UM A VISÃO EM TEMPO DE EXECUÇÃO E JÁ  CONSUMO ELA
CREATE OR REPLACE VIEW
    EMP AS (SELECT * FROM EMPLOYEES);
SELECT LAST_NAME FROM EMP;

--outro exemplo
SELECT DEPARTMENT_NAME, LAST_NAME
FROM   EMPLOYEES E JOIN DEPARTMENTS D
ON     (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
WHERE  D.DEPARTMENT_ID = 90;
--A IDEIA É TRANSFORMAR A INSTRUÇÃO ACIMA EM WITH
WITH
    --PRIMEIRA VISÃO
    EMP AS (SELECT LAST_NAME, DEPARTMENT_ID DEPT_ID FROM EMPLOYEES),
    --SEGUNDA VISÃO PARA JUSTAMENTE PERMITIR QUE EU FAÇA O JOIN
    DEPT AS (SELECT DEPARTMENT_ID DEPT_ID, DEPARTMENT_NAME FROM DEPARTMENTS)
SELECT DEPARTMENT_NAME, LAST_NAME
FROM EMP E JOIN DEPT D
ON (D.DEPT_ID = E.DEPT_ID)
WHERE D.DEPT_ID = 90;